// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBNXD6eqVeHZbWW5igtX_nMVmhaUw3gWI',
    appId: '1:738918661882:web:ce13e5859c06e12fe45343',
    messagingSenderId: '738918661882',
    projectId: 'healeasy-eea44',
    authDomain: 'healeasy-eea44.firebaseapp.com',
    storageBucket: 'healeasy-eea44.firebasestorage.app',
    measurementId: 'G-817LMKV1YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRHHSwU_YO3rFD-8skrpWnN8CVAOMfwk',
    appId: '1:738918661882:android:742a44c007ca17d5e45343',
    messagingSenderId: '738918661882',
    projectId: 'healeasy-eea44',
    storageBucket: 'healeasy-eea44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ015Kj1iEecyWljTF9G00adqn0KtqLb0',
    appId: '1:738918661882:ios:4e4e181c2b29600de45343',
    messagingSenderId: '738918661882',
    projectId: 'healeasy-eea44',
    storageBucket: 'healeasy-eea44.firebasestorage.app',
    iosBundleId: 'com.example.healeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ015Kj1iEecyWljTF9G00adqn0KtqLb0',
    appId: '1:738918661882:ios:4e4e181c2b29600de45343',
    messagingSenderId: '738918661882',
    projectId: 'healeasy-eea44',
    storageBucket: 'healeasy-eea44.firebasestorage.app',
    iosBundleId: 'com.example.healeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBNXD6eqVeHZbWW5igtX_nMVmhaUw3gWI',
    appId: '1:738918661882:web:051305100d340251e45343',
    messagingSenderId: '738918661882',
    projectId: 'healeasy-eea44',
    authDomain: 'healeasy-eea44.firebaseapp.com',
    storageBucket: 'healeasy-eea44.firebasestorage.app',
    measurementId: 'G-2P6LG6E41R',
  );
}
